### ISSUE TITLE
ContentView为nil报错

### ISSUE THREAD

**Issue by sishenyihuba** [an0/WLActivityViewController#3]
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'NSDictionaryOfVariableBindings failed because either one of the values is nil, or there's something wrong with the way the macro is being invoked.  Cannot assign value nil for key "contentView". Keys:(
    "_titleView",
    contentView
)'
 
调用棧报错在showTitleView 方法里
王凌大大,我使用Xcode9,跑在iOS11的模拟器上,报错信息如上.是不是后来APPLE在某个版本把ActivityViewController的细节改了?

**Comment by an0** [comment]
没错，我记得只支持到 iOS 10。我不再维护了，抱歉。
